### ISSUE TITLE
Contradictory user agreement and license

### ISSUE THREAD

**Issue by Saltssaumure** [LS-Wartaal/Radion-BD-Theme#2]
The user agreement and license have contradictory clauses, which creates an ambiguous situation with two negative effects:
- Users can argue that they can choose to follow the MIT license, which grants users permission to do as they like with this theme.
- Potential contributors see the user agreement and decide that making a PR might fall under the category of modifying or adapting the theme, and be discouraged from making helpful changes.

**Comment by LS-Wartaal** [comment]
Thanks; this issue has been resolved by removing the old "User Agreement" and editing the MIT LICENSE file.

**Comment by Saltssaumure** [comment]
You should change the title from "MIT License" to something else also, since the MIT license refers to a specific license which yours isn't anymore. And also change it in the README.md.
